### ISSUE TITLE
Write document on "Authoring Charts"

### ISSUE THREAD

**Issue by gabrtv** [deis/helm#101]
Though we outline our conventions in the `labels.md` file, chart authors need more of a "how-to" guide for authoring charts -- especially more complex ones.

**Comment by bacongobbler** [comment]
should this documentation live in deis/charts instead?

**Comment by gabrtv** [comment]
@bacongobbler the idea is that all helm and chart-related docs will live under the main helm repo (this one) so we don't wind up splitting documentation.  We want folks to browse from architecture to labels to how to author charts in the same doc hierarchy.
