### ISSUE TITLE
VOTE: Remove dependency on Kubernetes

### ISSUE THREAD

**Issue by technosophos** [deis/helm#106]
I have been experimenting with replacing our dependency on Kubernetes. I have some results to share, and I'd like to get feedback on this idea:

*Should we replace our Kubernetes dependency with a small shim API?*

As an ancillary question, should we move that shim API into the Deis namespace?

## The Evidence
We've all experienced the pain of using Kubernetes as a library.  It adds 20+ minutes to initial install time, and introduces substantial delay to all build operations. Each developer has over 100 packages of overhead to get Kubernetes to build as a library. And because Kubernetes is moving so quickly, we have to be very careful to pin on particular releases.

According to `du`, `helm` with Kubernetes requires 680M of disk space just for source code.

## The Alternative
When I looked at what parts of k8s we use, I realized that only a very small portion is needed. I decided to see if we could extract those parts, write a simpler utility layer on top, and have something more useful. The result is http://github.com/technosophos/kubelite.

It took only a few minutes to retrofit helm with kubelite.

- According to `du`, helm with kubelite consumes only 8M of disk space for source code.
- Compile time is reduced to a fraction of time, and runtime feels faster (though I haven't timed)
- We drop from 100 dependencies to 9

But then there is one absolutely *huge downside*: We now have a separate library to maintain. While the `v1` API for Kubernetes is relatively frozen, there will be work.

There is the potential that we contribute this upstream (in some way), or perhaps that we grow it into a useful standalone client library that is blessed by the Kubernetes community. But... essentially we're talking about maintaining a fork of a tiny slice of k8s.

Thoughts?

**Comment by technosophos** [comment]
To see the code: #107

**Comment by rimusz** [comment]
:+1: totally the way to go

**Comment by mattfarina** [comment]
:thumbsup: If I have to run `glide up` on another codebase with k8s as a dependency is till be too soon.

Though, I realize my vote really doesn't count :)

**Comment by bacongobbler** [comment]
It looks like [there is work on their end](https://github.com/kubernetes/kubernetes/issues/12290) to make imports easier, but I don't imagine they'll be making any huge changes any time soon. In that case, I'm for it if it brings compile time down. Otherwise I think we should stick with the pain of vendoring the kubernetes client APIs so we can always keep up-to-date without having to maintain a separate client library.

Is there any way we can just import github.com/kubernetes/kubernetes/pkg and not the entire repository? That might cut down on dependencies a bit if that was possible.

**Comment by aledbf** [comment]
Using `godep` only takes 9MB

```
{
	"ImportPath": "github.com/deis/helm",
	"GoVersion": "go1.5.1",
	"Packages": [
		"./..."
	],
	"Deps": [
		{
			"ImportPath": "bitbucket.org/ww/goautoneg",
			"Comment": "null-5",
			"Rev": "75cd24fc2f2c2a2088577d12123ddee5f54e0675"
		},
		{
			"ImportPath": "github.com/Masterminds/semver",
			"Comment": "1.0.0",
			"Rev": "6333b7bd29aad1d79898ff568fd90a8aa533ae82"
		},
		{
			"ImportPath": "github.com/Masterminds/vcs",
			"Comment": "1.1.4",
			"Rev": "324ed09b0d62f8b87ff792f5442ac351f3e734eb"
		},
		{
			"ImportPath": "github.com/beorn7/perks/quantile",
			"Rev": "b965b613227fddccbfffe13eae360ed3fa822f8d"
		},
		{
			"ImportPath": "github.com/codegangsta/cli",
			"Comment": "1.2.0-107-g942282e",
			"Rev": "942282e931e8286aa802a30b01fa7e16befb50f3"
		},
		{
			"ImportPath": "github.com/davecgh/go-spew/spew",
			"Rev": "3e6e67c4dcea3ac2f25fd4731abc0e1deaf36216"
		},
		{
			"ImportPath": "github.com/ghodss/yaml",
			"Rev": "588cb435e59ee8b6c2795482887755841ad67207"
		},
		{
			"ImportPath": "github.com/golang/glog",
			"Rev": "44145f04b68cf362d9c4df2182967c2275eaefed"
		},
		{
			"ImportPath": "github.com/golang/protobuf/proto",
			"Rev": "7f07925444bb51fa4cf9dfe6f7661876f8852275"
		},
		{
			"ImportPath": "github.com/google/gofuzz",
			"Rev": "bbcb9da2d746f8bdbd6a936686a0a6067ada0ec5"
		},
		{
			"ImportPath": "github.com/juju/ratelimit",
			"Rev": "772f5c38e468398c4511514f4f6aa9a4185bc0a0"
		},
		{
			"ImportPath": "github.com/matttproud/golang_protobuf_extensions/pbutil",
			"Rev": "fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a"
		},
		{
			"ImportPath": "github.com/pborman/uuid",
			"Rev": "ca53cad383cad2479bbba7f7a1a05797ec1386e4"
		},
		{
			"ImportPath": "github.com/prometheus/client_golang/model",
			"Comment": "0.4.0-1-g692492e",
			"Rev": "692492e54b553a81013254cc1fba4b6dd76fad30"
		},
		{
			"ImportPath": "github.com/prometheus/client_golang/prometheus",
			"Comment": "0.4.0-1-g692492e",
			"Rev": "692492e54b553a81013254cc1fba4b6dd76fad30"
		},
		{
			"ImportPath": "github.com/prometheus/client_golang/text",
			"Comment": "0.4.0-1-g692492e",
			"Rev": "692492e54b553a81013254cc1fba4b6dd76fad30"
		},
		{
			"ImportPath": "github.com/prometheus/client_model/go",
			"Comment": "model-0.0.2-12-gfa8ad6f",
			"Rev": "fa8ad6fec33561be4280a8f0514318c79d7f6cb6"
		},
		{
			"ImportPath": "github.com/prometheus/procfs",
			"Rev": "490cc6eb5fa45bf8a8b7b73c8bc82a8160e8531d"
		},
		{
			"ImportPath": "github.com/spf13/pflag",
			"Rev": "534019bcaea096fc0f0641afa2aed1e80cbb0ccc"
		},
		{
			"ImportPath": "github.com/ugorji/go/codec",
			"Rev": "821cda7e48749cacf7cad2c6ed01e96457ca7e9d"
		},
		{
			"ImportPath": "golang.org/x/crypto/ssh",
			"Rev": "c84e1f8e3a7e322d497cd16c0e8a13c7e127baf3"
		},
		{
			"ImportPath": "golang.org/x/net/context",
			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
		},
		{
			"ImportPath": "gopkg.in/yaml.v2",
			"Rev": "d466437aa4adc35830964cffc5b5f262c63ddcb4"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/api",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/auth/user",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/conversion",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/fields",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/labels",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/runtime",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/types",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/pkg/util",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "k8s.io/kubernetes/third_party/forked/reflect",
			"Comment": "v1.2.0-alpha.2-449-g1524d74",
			"Rev": "1524d7490a2dfbbcd2a98bcebd6518c06f3fbace"
		},
		{
			"ImportPath": "speter.net/go/exp/math/dec/inf",
			"Rev": "42ca6cd68aa922bc3f32f1e056e61b65945d9ad7"
		}
	]
}
```

**Comment by krancour** [comment]
I'd personally vote for looking into @aledbf's of using godeps instead.

**Comment by technosophos** [comment]
@aledbf -- that was with `du -h`? We should probably look into that. I'll tag @mattfarina gratuitously, too.

**Comment by mattfarina** [comment]
Hi folks! I'd like to jump in with some details that may help.

For anyone that doesn't know... Godep is useful for vendoring, that is storing the outside packages in your projects repo. A full copy of the repo (e.g., k8s) is kept in the `$GOPATH`. Anyone who is going to update the vendored material needs this. Godep then copies the relevant packages (sub-packages) into the vendored location (e.g. `vendor/`).

The first question is, do you want to store other projects packages in your repo?

For Glide there are two things that come to mind.

1. I want a cache (similar to what you're already doing with helm). It wasn't an issue until I started working with k8s. While the `$GOPATH` seems like a nice place for that you run into problems because you may want to fork... use a different repo for a time at the parents package location. That needs to be manually managed in the `$GOPATH` if that's the source.
2. If you do go down the vendored route (which Glide supports) we could add an option to remove the non-specified packages.

I would like to point out that the current vendoring strategy in Go (storing other peoples stuff in your repo) leads to unintended consequences. For example, k8s and it's dependencies currently list 4 different versions of `github.com/coreos/go-version` by different commit ids. Let's hope all the things continue to stay API compatible.

If anyone has questions I'm happy to talk about this.

**Comment by aledbf** [comment]
>  that was with du -h

Yes, here the output https://gist.github.com/aledbf/545e9c8739573a3f46b1

**Comment by technosophos** [comment]
Yeah, this becomes less enticing when it just means that all of the dependencies actually just go in $GOPATH. Maybe @sgoings could run a quick test or two through Travis and see what we gain or lose depending on the strategy

**Comment by sgoings** [comment]
I'm not sure what you're looking for @technosophos? What problem are you looking to solve? Travis will just do what we tell him to do. :wink:

**Comment by technosophos** [comment]
Right... I see what you mean. I was wondering if switching to Godeps would speed up Travis demonstrably. I suspect the answer is yes, but I'm wondering if that actually matters to the main questions we're trying to solve. As @mattfarina points out, developers will still have to install the full k8s (and al deps). It'll just go into $GOPATH instead of Godeps or vendor.

**Comment by mattfarina** [comment]
So, let's set aside the CI build time. I figured out how to really speed it up (pull request coming separately).

Instead there is a philosophical issue. To vendor, that is store the dependent packages inside the helm repo, or load them in each environment (which is typical of other setups like npm, composer, etc). This has to do more with managing and testing versions of dependencies.

For example, you could change the k8s version to `^1.1.0`. That is `>= 1.1.0, < 2.0.0`. This works in glide (master) now. The commit k8s is pinned to isn't a released version but some commit between versions near as I can tell. If you used `^1.1.0` on helm than each new k8s release with it's dependency chain could be tested and you could keep up to date and make sure the dependency tree work (if you've got good tests for it). You'd get dependency update integration as part of your regular testing.

This is more of a philosophical issue that an implementation one.

**Comment by mattfarina** [comment]
FYI, the pull request to speed up CI is at #126.
