### ISSUE TITLE
support discovery of Charts via other repositories for folks creating non-open source Charts

### ISSUE THREAD

**Issue by jstrachan** [deis/helm#109]
up to now we've been releasing the versioned kubernetes resources for running various apps in the [fabric8 project](http://fabric8.io/) using maven repositories as a canonical place to find them. We went with maven repositories as lots of folks we work with use upstream OSS code and have on premise stuff and need to work with both kinds of resources and lots of these folks already have maven repositories.

e.g. here you can search for them in maven centrals repository for many of fabric8's kubernetes resources:
http://search.maven.org/#search%7Cga%7C1%7Cl%3A%22kubernetes%22

right now we've been releasing OpenShift template JSON; but we'll happily generate helm Charts too. It would be nice if there was some mechanism to discover Charts in other repositories though.

e.g. I can imagine folks wanting to use a helm-like tool for internal Charts which are not public on the internet and so can't be submitted as a PR on the public helms repository.

I guess an easier option than supporting maven repository searching would be to support multiple git repositories for the charts repositories; so there can be the main public OSS helm git repo; then users can have their own internal git repos?

**Comment by bacongobbler** [comment]
I think that would be a good feature. `pip` and other tools allow communicating with another index other than pypi.python.org, and `brew` has `brew tap`. Having the ability to pick and choose repositories to install from like `brew tap` would be a good feature to have at some point.

**Comment by sgoings** [comment]
I believe we already have the beginnings of support for multiple git repos via:

```
GLOBAL OPTIONS:
   --repo "https://github.com/deis/helm"	The remote Git repository as an HTTP URL [$HELM_REPO_URL]
```

Example:
```
./bin/helm --repo https://github.com/bacongobbler/charts update
---> Creating /Users/sethgoings/.helm
---> Creating /Users/sethgoings/.helm/cache
---> Creating /Users/sethgoings/.helm/workspace
---> Cloning repo into "/Users/sethgoings/.helm/cache". Please wait.
---> Updated /Users/sethgoings/.helm/cache from https://github.com/bacongobbler/charts
```

**Comment by bacongobbler** [comment]
see also #111
