### ISSUE TITLE
helm create errors

### ISSUE THREAD

**Issue by rimusz** [deis/helm#121]
Used the latest helm binary from bintray, `helm create` complains about a missing '~/.helm/cache/skel' folder
Manually creating it, did the trick

**Comment by kgrvamsi** [comment]
I'm eager to know on how you downloaded the binary from bintray.......it was bit confusing for me that i couldn't able to get the binary :(

**Comment by rimusz** [comment]
@kgrvamsi just click the link the `CI build pipeline: Download | git-xxxxx` ant then Files section

**Comment by kgrvamsi** [comment]
:+1: 

Yes i figured out later when i read the README in clear

**Comment by bacongobbler** [comment]
closing in favour of #127 and #130
