### ISSUE TITLE
helm edit errors

### ISSUE THREAD

**Issue by rimusz** [deis/helm#122]
`helm edit` complains about the missing:
 `/.helm/workspace/charts/nginx/Chart.yaml: no such file or directory`
`/.helm/workspace/charts/nginx/manifests: no such file or directory/

'helm create nginx' of course command did run before

**Comment by technosophos** [comment]
I think this might have been resolved when I fixed another path error. Can you still reproduce this @rimusz ?

**Comment by rimusz** [comment]
no, I cannot, it works fine now.
