### ISSUE TITLE
Running `helm` with an unknown command: "No help topic for 'run'"

### ISSUE THREAD

**Issue by carmstrong** [deis/helm#128]
We should probably just emit the helptext here.

```console
➜  ~  helm run lololol
No help topic for 'run'
```

**Comment by michelleN** [comment]
@carmstrong There is no run command. DId you want to see something else as output?

**Comment by bacongobbler** [comment]
I guess if there's no such command, a better error message would be `command 'run' not found. See 'helm help' for usage information` would be more informational :)

**Comment by michelleN** [comment]
absolutely. +1 @bacongobbler

**Comment by adamreese** [comment]
its a bug with the cli package

```
% etcdctl run
No help topic for 'run'
```

**Comment by carmstrong** [comment]
Yeah, I was just looking now at setting a default when the subcommand doesn't match -- I would love to print "%s isn't a valid command", and then the usage blob.

**Comment by adamreese** [comment]
```
cli.Command{
	Name:  "run",
	Usage: "only use in case of fire",
	Action: func(c *cli.Context) {
		log.Warn("RUN")
}
```

**Comment by carmstrong** [comment]
`helm fireinthehole`.

I filed https://github.com/codegangsta/cli/issues/293 to inquire about adding a default subcommand action.

**Comment by technosophos** [comment]
There's already a hook for that. See the App object: `CommandNotFound func(context *Context, command string)`
