### ISSUE TITLE
missing skel directory in cache path

### ISSUE THREAD

**Issue by michelleN** [deis/helm#130]
```
elm [master]$ make build
go build -o bin/helm -ldflags "-X main.version=git-2993d74" helm/helm.go
helm [master]$ ./bin/helm create chartname
[ERROR] Could not find /Users/dev/.helm/cache/skel: stat /Users/dev/.helm/cache/skel: no such file or directory
```

**Comment by michelleN** [comment]
@slack @technosophos should the skel directory get copied to the cache path on helm update?

**Comment by michelleN** [comment]
update: After talking with @slack, we'll want to copy the skel directory to cache/skel as part of `helm update`

**Comment by adamreese** [comment]
Rather than copy a directory, we could generate a skel chart from a template that included the name.
```
$ ./helm create mychart
```
In `~/.helm/workspace/charts/mychart/Chart.ymal`
```
name: mychart
home: http://example.com/your/project/home
version: 0.0.1
...
```

**Comment by michelleN** [comment]
@adamreese Initially, we'll want to copy the skel directory into cache to use in the first place, but yes, I really like the idea of customizing chart generation with the given name!

**Comment by michelleN** [comment]
@adamreese's solution to this is pretty dope so handing this over to him! Thanks!
