### ISSUE TITLE
Notify user of update to Helm

### ISSUE THREAD

**Issue by technosophos** [deis/helm#136]
As a user, I would like to be notified when a newer stable version of Helm is available.

In the last hour, both @gabrtv and @jackfrancis have asked about this, and it sure would be nice to have in the very first release.

One possible (and cheap) solution would be to have Helm query the Releases available for the Helm repo, and do a simple tag-based match to see if it is on that release.

We'll shoot for something like this:

```
$ helm update
---> A newer version of Helm is available. Download version 1.2.3: http://github.com/deis/helm/...
---> # Rest of the normal output
```

For this issue, it'll be a non-goal to actually install a newer version, though we should probably look into this in the future.

**Comment by rimusz** [comment]
+1
