### ISSUE TITLE
helm edit - shell editor

### ISSUE THREAD

**Issue by rimusz** [deis/helm#144]
shall we store the set editor to .helm folder for example?

as it always asks for `must set shell $EDITOR` if I open a new shell

**Comment by Joshua-Anderson** [comment]
@rimusz I think a better approach would be to add the `$EDITOR` variable to your bash profile instead. This would keep helm compatible with other unix tools like git.

**Comment by bacongobbler** [comment]
Yep. If we are to follow stabdard idioms, relying on $EDITOR as we do now is the "proper" way to do things. See https://en.m.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables

**Comment by rimusz** [comment]
it is fine with me, but I'm just concerned about beginner users, might be a good idea to  put a short explanation to  `helm edit` how save $EDITOR to .bash_profile?
