### ISSUE TITLE
bump to v0.1.0

### ISSUE THREAD

**Issue by bacongobbler** [deis/helm#167]
helm is currently at v0.0.1. When we deem it is the right time to do so, we should bump to v0.1.0.

**Comment by technosophos** [comment]
LGTM. Anyone object to tagging?

**Comment by bacongobbler** [comment]
version wasn't changed with the bump:

```
><> cat helm.go | grep 0.0.1
var version = "0.0.1"
```

Shall I make a followup PR for that?
