### ISSUE TITLE
prettyprint package missing from glide-full.yaml

### ISSUE THREAD

**Issue by bacongobbler** [deis/helm#169]
https://github.com/deis/helm/commit/3e6efa2810014b8324a50f3064b5dbfd661dbf39 accidentally removed github.com/deis/pkg/prettyprint from its dependencies, causing new builds to fail with the following:

```
><> make build
go build -o bin/helm -ldflags "-X main.version=+839fc02" helm.go
log/log.go:9:2: cannot find package "github.com/deis/pkg/prettyprint" in any of:
        /home/bacongobbler/go/src/github.com/deis/helm/vendor/github.com/deis/pkg/prettyprint (vendor tree)
        /usr/local/go/src/github.com/deis/pkg/prettyprint (from $GOROOT)
        /home/bacongobbler/go/src/github.com/deis/pkg/prettyprint (from $GOPATH)
Makefile:16: recipe for target 'build' failed
make: *** [build] Error 1
```

Travis doesn't show this because we [cache vendor/](https://github.com/deis/helm/blob/master/.travis.yml#L12), so we don't see it unless the cache is cleared.

**Comment by technosophos** [comment]
Good catch!

**Comment by bacongobbler** [comment]
I've just added the dependency to glide.yaml and will re-generate glide-full.yaml once I get a build working again :)

Is there a shortcut you use? `glide up && make build && glide ...`?
