### ISSUE TITLE
`helm uninstall`

### ISSUE THREAD

**Issue by technosophos** [deis/helm#17]
Implement as described in the design document.

**Comment by technosophos** [comment]
I can't find a clear definition of what an uninstall would do.

@sgoings is assuming (I think) that this would do a `kubectl delete`. Do we want to do that?

Is `uninstall` removing the `workspace/charts/$CHART for the named package?

**Comment by sgoings** [comment]
My idea was that uninstall would be the inverse of install - so it'd just be a wrapper around `kubectl delete`. It should roll back the workspace to whatever existed before an install of that chart.

**Comment by technosophos** [comment]
Uh-oh... I just saw that @michelleN is assigned to this. I had just whipped it out along with the `helm install` command. I'm sorry.
