### ISSUE TITLE
Use a more current and more stable version of Kubernetes, if possible.

### ISSUE THREAD

**Issue by jackgr** [deis/helm#198]
The path pkg/apis/experimental existed only in v1.2.0-alpha.0. Folks have moved on.

**Comment by bacongobbler** [comment]
It's the last known version that we've tested internally (anecdotally, I'm still on v1.0.6). Is there a version of kubernetes that has been known to actually deploy without errors? From my own testing on v1.1.0+ none properly worked with Vagrant.

**Comment by sgoings** [comment]
Also see #139

**Comment by technosophos** [comment]
I'm going to close this as a duplicate of #139. We definitely need to get this updated. I'll spend the time figuring out what we should be running on.
