### ISSUE TITLE
No binaries on Bintray.

### ISSUE THREAD

**Issue by elsonrodriguez** [deis/helm#200]
Was trying to play with this, but the builds on bintray don't have any downloadable binaries.

https://bintray.com/deis/helm/helm/view

Will build from source in the meanwhile.

**Comment by sgoings** [comment]
There are binaries located on the "files" tab on the link you specified. A more direct link would be: 

https://bintray.com/deis/helm/helm/view#files

We will have a nice way to get the latest release version of helm when http://helm.sh goes live.

**Comment by rimusz** [comment]
@elsonrodriguez just click on Files and you will see binary builds there
<img width="874" alt="screen shot 2015-11-08 at 08 58 29" src="https://cloud.githubusercontent.com/assets/5215395/11021478/0aa042e0-85f7-11e5-945a-adb3d08f1283.png">

**Comment by rimusz** [comment]
I think we can close this one

**Comment by elsonrodriguez** [comment]
Derp, thanks for pointing me in the right direction.

I believed the lie the page told me: "No direct downloads selected for this package."
