### ISSUE TITLE
Provide better information after a chart is installed

### ISSUE THREAD

**Issue by sgoings** [deis/helm#206]
When I ran:

```
./helm install jenkins
```

the output was:

```
---> No chart named "jenkins" in your workspace. Fetching now.
---> Running `kubectl create -f` ...
pods/jenkins
---> Done
========================================
# Jenkins

Jenkins CI is the leading open-source continuous integration server.
========================================
```

It would be nice if I was told how to interact with this package right away after installation (mainly a URL to hit to login to Jenkins).

**Comment by michelleN** [comment]
@sgoings Maybe we could create a "next steps" or some field in the Chart.yaml file that would print after the `helm install` command runs?

**Comment by sgoings** [comment]
That's essentially what I was thinking. Another option might be to parameterize/templatize the Chart.yaml "details" field.

**Comment by technosophos** [comment]
That text comes from the README file.

The Selenium README is a great example of how we should be writing these. https://github.com/deis/charts/pull/23

**Comment by michelleN** [comment]
+1

**Comment by technosophos** [comment]
Marking this closed. See the new `awesome.md` in docs.
