### ISSUE TITLE
Can't build on OS X

### ISSUE THREAD

**Issue by statik** [deis/helm#211]
Following the instructions in the README to build, I got an error about unable to find `glide`. After searching, I figured out to `brew install glide`. Now `make bootstrap` gives me this error:
```
glide -y glide-full.yaml up
Oops! interface conversion: yaml.Node is yaml.Map, not yaml.List
make: *** [bootstrap] Error 1
```

Trying this with master as of 36a4d4c4f70adf8fb574398387403f8843aac1cf

**Comment by bacongobbler** [comment]
@statik try a more recent version of glide. This issue is fixed in v0.7.0 AFAIK.

**Comment by mattfarina** [comment]
@statik I can confirm what @bacongobbler said. Update brew to get the latest and the problem should be fixed. The error you're getting tells me it's a version prior to 0.7.0.

**Comment by statik** [comment]
Thanks! Updating glide did indeed fix things for me.

On Wednesday, November 11, 2015, Matt Farina <notifications@github.com>
wrote:

> @statik <https://github.com/statik> I can confirm what @bacongobbler
> <https://github.com/bacongobbler> said. Update brew to get the latest and
> the problem should be fixed. The error you're getting tells me it's a
> version prior to 0.7.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deis/helm/issues/211#issuecomment-155792966>.
>


-- 
-- 
Elliot Murphy
