### ISSUE TITLE
Ensure/create cache directory if it doesn't exist

### ISSUE THREAD

**Issue by sgoings** [deis/helm#40]
When I run `helm update` on a fresh system, I get:

```
 ~/go/src/github.com/deis/helm  ⑂ master    helm update
Could not change to directory "/Users/sethgoings/.helm/cache": chdir /Users/sethgoings/.helm/cache: no such file or directory
```

**Comment by technosophos** [comment]
Is that the only output generated? Had you created `.helm` first?

**Comment by sgoings** [comment]
Updated entire output above. `helm` exited at that point.

To get up and running I had to manually create `~/.helm`

**Comment by technosophos** [comment]
Okay. The code currently creates a `.helm` dir and its subdirs when it detects that no helmdir exists. We should augment this to also make sure cache and workspace are created.

This is in `ensureHome` in `update.go`.
