### ISSUE TITLE
Publish the mkdocs site

### ISSUE THREAD

**Issue by gabrtv** [deis/helm#44]
We have integrated documentation that you can see locally with `mkdocs` (if you install it on your workstation).  In order to make the docs public, we should probably:

1. Figure out a deployment and hosting solution for the documentation site
2. Style the docs site with something other than the default `readthedocs` theme

ping @jackfrancis

**Comment by mboersma** [comment]
> Figure out a deployment and hosting solution for the documentation site

ReadTheDocs.org can host MkDocs projects, as one option.

**Comment by jackfrancis** [comment]
merci @mboersma 

@gabrtv what do you think of hosting the docs a-là:

http://brewmaster.readthedocs.org/en/latest/

We could link to such a readthedocs-hosted page from the Helm-branded site (e.g., `helm.sh`) via a Helm-branded link button. Something like that.

**Comment by gabrtv** [comment]
Seems like ReadTheDocs or GitHub Pages are the best options.  I defer to @mboersma for such matters. :)

**Comment by jackfrancis** [comment]
Related PR: https://github.com/deis/helm/pull/98

**Comment by jackfrancis** [comment]
@gabrtv For your consideration:

http://helm.readthedocs.org/en/latest/

That URL will keep up-to-date with changes to master (in particular what we care about is changes to mkdocs.yml and its referenced .md files).

**Comment by bacongobbler** [comment]
+1

**Comment by gabrtv** [comment]
Over time I'd like to see docs hosted at http://helm.sh/docs/ .. but http://helm.readthedocs.org/en/latest/ will do nicely for 0.1.0.  Closing.
