### ISSUE TITLE
Add --chart-path (and -p) to helm install

### ISSUE THREAD

**Issue by sgoings** [deis/helm#47]
To make it easier to contribute a `Chart` we'd like to be able to run `helm install` and pass in a path to a chart with `[--chart-path|-p]=[.|<path>]?`

This way people can grab a released version of the `helm` cli, build a new component/package (in a separate repo) and test it locally (spin up kubernetes cluster, install, uninstall) before they submit a PR for the Chart back to the helm repo. Eventually we'll grease the process for people wanting to upload/update helm charts upstream. (maybe something like `helm pr`)

**Comment by technosophos** [comment]
The idea is that `--chart-path` should point to a directory that contains a `Chart.yaml` file and a `manifests/` directory.

**Comment by technosophos** [comment]
Seems to me that in this case, Helm should _always_ overwrite the locally fetched copy with the specified chart.
