### ISSUE TITLE
`helm remove` to remove a chart from the workspace

### ISSUE THREAD

**Issue by technosophos** [deis/helm#55]
While `helm fetch` copies a chart into the workspace, `helm remove` should remove the chart. It should probably have the alias `helm rm`.

**Comment by technosophos** [comment]
@michelleN would you like to take this one since I swiped `helm uninstall` out from under you? (Again, sorry... my bad)

**Comment by michelleN** [comment]
haha yeah I'll take it. no worries. thanks!
