### ISSUE TITLE
`helm create` command

### ISSUE THREAD

**Issue by technosophos** [deis/helm#7]
We should streamline the developer experience by adding a `helm create` command.

Purpose: make it easy for a wannabe Chart developer to become a real chart developer.

Usage:

```
$ helm create myproject
----> Creating project in $HELM_HOME/workspace/charts/myproject
----> Creating $HELM_HOME/charts/myproject/manifests
----> Adding Chart.yaml
```

(Or something like that)

For bonus points, implement `helm push myproject` (or some other push-like verb) to copy the new chart to the `$HELM_HOME/cache/charts/myproject` directory so it can be submitted as a pull request. (see the logic in `actions.Fetch()`).

**Comment by gabrtv** [comment]
Closed by #34.
