### ISSUE TITLE
`go get github.com/deis/helm/...` too many dependencies

### ISSUE THREAD

**Issue by rimusz** [deis/helm#70]
`go get github.com/deis/helm/...` needs too many dependencies to compile go binary

using glide I can compile at no problem

**Comment by technosophos** [comment]
Yeah, we're up to something like 130+ at this point. Almost all come via Kubernetes. I am working on something that will cut that back down to about 6: https://github.com/technosophos/kubelite

**Comment by rimusz** [comment]
ok, cool

**Comment by ingvagabund** [comment]
Any plans to provide Godeps.json or GLOCKFILE to track dependencies in future?

**Comment by bacongobbler** [comment]
@ingvagabund we're using glide. Check out glide.yml :)

**Comment by ingvagabund** [comment]
Nice to meet you glide :). Thanks @bacongobbler

**Comment by technosophos** [comment]
Basically, we've decided to just swallow the fact that k8s comes with a lot of dependencies.
