### ISSUE TITLE
`helm edit`

### ISSUE THREAD

**Issue by technosophos** [deis/helm#8]
Homebrew provides a nice little convenience tool called `brew edit` to help formula authors.

Could we provide something similar for `helm`? @gabrtv has some ideas about how we might implement this. Perhaps he can chime in here.

**Comment by gabrtv** [comment]
I really want to see a nice contributor workflow that features:

 * `helm create mychart`
 * `helm edit mychart`

..followed by a straightforward branch and pull request model -- like Homebrew.

However, Homebrew has the advantage that formulas are a single file.  In Helm,  charts are by nature multiple files.  To work around this, I propose we have `helm edit` construct a tempfile that consists of all files in the chart delimited by something like: `--- <filename>`.  When we save changes, we parse the constituent files and flush them down to disk.  This gives us the best of both worlds.

Thoughts?

**Comment by BVrolyk** [comment]
Don't we need to worry about recursion and loops if we're _including_ files in the edit process?

**Comment by technosophos** [comment]
That is actually something we need to be careful about. If people start using symlinks, we'll need to make sure we don't end up with either broken links or looped links. `fetch` is probably the most likely to hit that problem, so I'll do some stuff there.

**Comment by gabrtv** [comment]
@BVrolyk there shouldn't be any recursion issues here because we're not actually doing any includes.  It's just a single-file view of what's in the chart directory.  To my mind, the trickiest bits are:

1. Finding the right delimiter so we don't get confused with valid manifest content
2. Ensuring the filenames are handled carefully so we don't pollute the local disk, i.e. `../../../../../../etc/passwd`

The idea would be to walk the chart directory and construct a tempfile that looks something like this:

```
--- Chart.yml
name: ponycorn
home: http://github.com/technosophos/ponycorn
version: 1.0.3
description: The ponycorn server
maintainers:
  - Matt Butcher <mbutcher@deis.com>
dependencies:
  - name: nginx
    version: 1.9 < x <= 1.10
details:
  This package provides the ponycorn server, which requires an existing nginx
  server to function correctly.
--- manifests/alpine-sleeper.yaml
apiVersion: v1
kind: Pod
metadata:
  name: alpine-sleeper
spec:
  restartPolicy: Never
  containers:
  - name: waiter
  image: "Alpine:3.2"
    command: ["/bin/sleep","9000"]

**Comment by BVrolyk** [comment]
Yes, make sense.  Thx,

Beau

**Comment by gabrtv** [comment]
I've begun work on a PR that implements this.
