### ISSUE TITLE
Rename skel, test, and docs to _skel, _test, and _docs.

### ISSUE THREAD

**Issue by technosophos** [deis/helm#92]
Per #90, we will move the source code of helm up a directory. To better accomodate the Go tools, we should rename the above directories. (Go ignores directories prefixed with `_`). That way, if we end up putting any Go-like code in these directories, the Go runtime will ignore them.

**Comment by bacongobbler** [comment]
since we're breaking out all of the external libs into places like deis/pkg, wouldn't it make more sense to store the source code in something like

**Comment by michelleN** [comment]
@bacongobbler - I also like that project structure. If we went that route, would there be any additional complexities using go tools with the helm project that you might know of? @technosophos any thoughts?

**Comment by bacongobbler** [comment]
There would be a bit more internal complexity compared to your run-of-the-mill Go project, but I believe the benefits outwiegh the costs.

For starters, we'd have to ensure that the $GOPATH is set to $GOPATH/src/github.com/deis/helm when running a build, which some go tools would pick up automatically ([gb](https://github.com/constabulary/gb) does this by recursively searching for a `src/` directory).

One project that immediately comes to mind that uses this project structure would be [confd](https://github.com/kelseyhightower/confd). I help maintain that project though so I may be a bit biased, but I believe that project structure works quite well.

For example, the project structure (in my mind) would look something like this:

```
etc/helm/skel/
docs/
tests/
tests/ci/
src/
  helm.go
  helm/
    model/
    manifest/
    [...]
```

In helm.go, importing helm libraries would no longer be `github.com/deis/helm/helm/model`, but instead just `helm/model`. `glide` would bootstrap vendored dependencies into `./src/vendor`, which then Go with the 1.5 vendor experiment would work as normal: 

```
$ cd helm
$ make bootstrap
$ GOPATH=$PWD go build src/...
```

In terms of benefits to this project structure, forking and contributing to the project just got a heck of a lot easier. The user doesn't have to import the project into $GOPATH/src/github/com/deis/helm to build the project, which has burned us in the past with deis who are new to Go. More experienced Go developers may be ticked off that we're not using Go's native tooling "The Way It Was Meant To Be:tm:", but we're already using `glide` so they already have something else to gripe about ;)

One cost of this route means that the project can no longer be used as a library, but we can always split those out of the project like we do with [pkg](https://github.com/deis/pkg).

If it was up to me, this is the project structure that I would tinker with. :)

**Comment by michelleN** [comment]
That makes a lot of sense to me. :) :+1: @bacongobbler

**Comment by technosophos** [comment]
My main reservation is that I don't want to end up fighting with Go's toolchain to make stuff build. Given the proposal above, we would _definitely_ find ourselves having to work around tooling. We'd also be breaking developer expectations of how things work.

The absolutely most painful thing about confd is that you simply can't use it as a library. And that's largely because of the way they structure the project. I can definitely think of parts of Helm that I hope are re-usable. (`model/*` is an example). So it is very important that someone should be able to `go get github.com/helm/.../model` (where `...` is whatever structure we add) and come away with a working library. At gophercon, rsc even expressed some frustrations with the choices gb made in these regards.

So I am in favor of doing something that doesn't involve munging the development environment at all, and which works with the core `go` tools as they are today.

Finally, to circle back around to the main topic... we actually don't _have_ to rename any of these directories. I opened the issue because it seems to be the standard way of doing things in Go projects, but unless we're planning on storing lots of .go files in these directories (and using a naive `go build` to build it all), this isn't really much of a concern. So we could just close this issue and not do anything.

If we end up using `github.com/deis/helm/src/helm`, that's _okay_, but we need to consistently reference it by that fully qualified path. And for what it's worth, that change would be unnecessary. We could just leave it as `deis/helm/helm`.

**Comment by bacongobbler** [comment]
Most of my griping is to keep the docs as `docs` unless they were written in Go (pls no... MkDocs is great). Everything else can be underscored. I'd imagine that we might write some tests in Go in the future if it made sense, so having things like `_skel` and `_tests` make sense so we're not accidentally running tests when naively running `go get`.

I also agree with your concerns about how confd cannot be used as a library (that's still something we have to figure out to this day) so following the herd and using core Go tools would make sense from an adoption point of view. The proposed structure is still unproven but it makes "sense" if we were language independent and didn't care as much about re-usability, but did care about internal project structure. I concede to you. :+1:

**Comment by technosophos** [comment]
Sorry to sort of steamroll the issue. But thanks, @bacongobbler, for tolerating my ranting. ;-)
