### ISSUE TITLE
Publish a "latest-good" build to Bintray (or similar)

### ISSUE THREAD

**Issue by sgoings** [deis/helm#93]
Now that we have the charts repo and helm repo separated and a fast approaching #86 feature (being able to install with `--chart-path`), we need to make sure that it's easy to use helm as an end user and not a helm core developer.

This should also reduce the barrier to entry as it has historically been sort of difficult for even those involved in the project to get all the go dependencies included properly.

**Comment by technosophos** [comment]
At this point, I would say that this is a very high priority for us.
